const ROUTER_PATH = {
  COURS: '/cours',
  COURS_ADVANCED: '/coursadvanced',
  COURS_PLUS: '/coursplus',
  DIET: '/diet',
  DIET_ACHAT: '/dietachat',
  DIET_ADVANCED: '/dietadvanced',
  DIET_HISTORIQUE: '/diethistorique',
  DIET_HISTORIQUES: '/diethistoriques',
  DIET_PLUS: '/dietplus',
  DIET_PLUS_PANIER: '/dietpluspanier',
  DIET_PLUS_SELECTION: '/dietpluspanierselection',
  DIET_POPUP_CMD: '/dietpopupcmd',
  DIET_POPUP_FACTURE: '/dietpopupfacture',
  DIET_POPUP_PANIER: '/dietpopuppanier',
  EXERCICE_LIST: '/exercicelist/:bodypart',
  EXERCICES: '/exercices',
  EXERCICES_LEVEL: '/exercicelevel',
  FORGOT_YOUR_PWD: '/forgotyourpassword',
  FORGOT_YOUR_PWD_CHOOSE: '/forgotyourpasswordchoose',
  HOME: '/home',
  HOME_PARAMS: '/',
  IDENTIFICATION: '/identification',
  INTRO: '/intropart1',
  MENTION: '/mention',
  PARCOURS: '/parcours',
  PARCOURS_ADVANCED: '/parcoursadvanced',
  PERSONAL_DETAILS: '/personaldetails',
  PERSONAL_DETAILS_ABO: '/personaldetails/abo',
  PERSONAL_DETAILS_INFO_PERSO: '/personaldetails/infoperso',
  PERSONAL_DETAILS_LANG: '/personaldetails/lang',
  PERSONAL_DETAILS_LEVEL: '/personaldetails/level',
  PERSONAL_DETAILS_PORTE_FEUILLE: '/personaldetails/portefeuille',
  PERSONAL_DETAILS_PROFIL: '/personaldetails/profil',
  PRICE: '/price',
  RESET: '/reset',
  SIGNIN: '/signin',
  SIGNIN_PLATEFORM: '/signinplatform',
  SIGNUP: '/signup',
  SIGNUP_LEVEL: '/signup/level',
  SIGNUP_PROFIL: '/signup/profil',
  SIGNUP_TYPE: '/signup/type',
  TITRE: '/titre',
  TYPE: '/type',
  VIDEO: '/video',
};

export default ROUTER_PATH;
